dv\SSW2014Bundle\Entity\Category:
  type: entity
  table: category
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    name:
      type: string
      length: 255
      unique: true
    slug:
      type: string
      length: 255
      unique: true
    created_at:
      type: datetime
    updated_at:
      type: datetime
      nullable: true
  oneToMany:
    category_entities:
      targetEntity: EntityCategory
      mappedBy: category
  lifecycleCallbacks:
    prePersist: [ prePersistTask ]
    preUpdate: [ preUpdateTask ]
