dv\SSW2014Bundle\Entity\Query:
  type: entity
  table: query
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    name:
      type: string
      length: 255
      unique: true
    label:
      type: string
      length: 255
      unique: true
    query:
      type: text
    created_at:
      type: datetime
    updated_at:
      type: datetime
      nullable: true
  lifecycleCallbacks:
    prePersist: [ setCreatedAtValue ]
    preUpdate: [ setUpdatedAtValue ]
