dv\SSW2014Bundle\Entity\Type:
  type: entity
  table: type
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    resource:
      type: string
      length: 255
      unique: true
    created_at:
      type: datetime
    updated_at:
      type: datetime
      nullable: true    
  oneToMany:
    entities:
      targetEntity: Entity
      mappedBy: type
  lifecycleCallbacks:
    prePersist: [ setCreatedAtValue ]
    preUpdate: [ setUpdatedAtValue ]
