category_like:
    pattern:  /like
    defaults: { _controller: "dvSSW2014Bundle:Category:like" }
    requirements: { _method: post }

category:
    pattern:  /
    defaults: { _controller: "dvSSW2014Bundle:Category:index" }

category_show:
    pattern:  /{id}/show
    defaults: { _controller: "dvSSW2014Bundle:Category:show" }

category_new:
    pattern:  /new
    defaults: { _controller: "dvSSW2014Bundle:Category:new" }

category_create:
    pattern:  /create
    defaults: { _controller: "dvSSW2014Bundle:Category:create" }
    requirements: { _method: post }

category_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "dvSSW2014Bundle:Category:edit" }

category_update:
    pattern:  /{id}/update
    defaults: { _controller: "dvSSW2014Bundle:Category:update" }
    requirements: { _method: post|put }

category_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "dvSSW2014Bundle:Category:delete" }
    requirements: { _method: post|delete }
