dv_ssw2014_query:
    resource: "@dvSSW2014Bundle/Resources/config/routing/query.yml"
    prefix: /query

dvSSW2014Bundle_topic:
    resource: "@dvSSW2014Bundle/Resources/config/routing/topic.yml"
    prefix:   /topic

dv_ssw2014_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: dvSSW2014Bundle:Default:index }
