dv_ssw2014_category:
    resource: "@dvSSW2014Bundle/Resources/config/routing/category.yml"
    prefix: /category

dv_ssw2014_entity:
    resource: "@dvSSW2014Bundle/Resources/config/routing/entity.yml"
    prefix: /entity

dv_ssw2014_entitycategory:
    resource: "@dvSSW2014Bundle/Resources/config/routing/entitycategory.yml"
    prefix: /entity_category

dv_ssw2014_query:
    resource: "@dvSSW2014Bundle/Resources/config/routing/query.yml"
    prefix: /query

dv_ssw2014_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: dvSSW2014Bundle:Default:index }
